### ISSUE TITLE
Choose Cache Root window is not fully visible

### ISSUE THREAD

**Issue by nikolay-borzov** [gittromney/Playnite-NowPlaying#17]
Playnite: 10.34
NowPlaying: 1.4.1
Theme: Default
Theme API: 2.6.0

Choose Cache Root window button at the bottom are cut.

![image](https://github.com/user-attachments/assets/981725b8-5a2d-4390-84d9-e811b87b54f4)

There is an error in `Playnite.log`:
```
ERROR|GameMenu:Failed to get menu items from plugin NowPlaying Game Cacher
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NowPlaying.NowPlaying.GetGameMenuItems(GetGameMenuItemsArgs args) in C:\Dev\GitHub\Playnite-NowPlaying\source\NowPlaying.cs:line 825
   at Playnite.DesktopApp.Controls.GameMenu.AddExtensionItems(List`1 games) in C:\projects\playnite\source\Playnite.DesktopApp\Controls\Menus\GameMenu.cs:line 586
```

**Comment by gittromney** [comment]
Thanks. I'm reworking windows to better accommodate larger fonts. Stay tuned.

**Comment by gittromney** [comment]
HI, the latest release should address this problem for you (v1.4.2). Please check it out.
--gr

**Comment by nikolay-borzov** [comment]
Looks great now. Thanks for the fix!

![image](https://github.com/user-attachments/assets/d2ee18ea-04f7-4833-a943-46e3bf80628e)

**Comment by gittromney** [comment]
Sure thing. closing this issue. --gr.
